import sys
sys.path.append("./src")
from memory import MemoryService

def test_memory_module():
    print("🚀 Starting Memory Module Test...")

    # 1. 初始化
    memory = MemoryService()

    # 2. 准备测试数据 (模拟科学文献和反思)
    reflection_text = "Analysis Failed: The causal graph generated by PC algorithm was cyclical, which violates the DAG assumption. I need to check the data preprocessing step."
    paper_text = "The PC algorithm assumes that the underlying causal structure is a Directed Acyclic Graph (DAG). It uses conditional independence tests."

    # 3. 存储数据 (带有 Metadata)
    print("\n📥 Inserting memories...")
    memory.save_memory(
        reflection_text, metadata={"type": "reflection", "status": "failed"}
    )
    memory.save_memory(
        paper_text, metadata={"type": "knowledge", "topic": "PC_algorithm"}
    )

    # 4. 检索测试
    query = "Why did the causal discovery fail?"
    print(f"\n🔍 Querying: '{query}'")

    results = memory.retrieve_memories(query, limit=2)

    # 5. 验证结果
    for i, res in enumerate(results):
        print(f"--- Result {i+1} (Score: {res['score']:.4f}) ---")
        print(f"Content: {res['text']}")
        print(f"Metadata: {res['metadata']}")

    # 简单的断言
    assert len(results) > 0
    assert "cyclical" in results[0]["text"] or "cyclical" in results[1]["text"]
    print("\n✅ Test Passed!")


if __name__ == "__main__":
    test_memory_module()
